// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using magero_store.Data;

#nullable disable

namespace magero_store.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("magero_store.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "High-performance gaming laptop with RTX 3080",
                            Nombre = "Gaming Laptop",
                            Precio = 1999.99m,
                            UrlImagen = "https://images.unsplash.com/photo-1603302576837-37561b2e2302"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Premium wireless earbuds with noise cancellation",
                            Nombre = "Wireless Earbuds",
                            Precio = 199.99m,
                            UrlImagen = "https://images.unsplash.com/photo-1590658087412-d1d9f559ef20"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "32-inch 4K HDR Professional Monitor",
                            Nombre = "4K Monitor",
                            Precio = 699.99m,
                            UrlImagen = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "RGB Mechanical Gaming Keyboard",
                            Nombre = "Mechanical Keyboard",
                            Precio = 159.99m,
                            UrlImagen = "https://images.unsplash.com/photo-1595225476474-87563907a212"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Wireless Gaming Mouse with 25K DPI",
                            Nombre = "Gaming Mouse",
                            Precio = 129.99m,
                            UrlImagen = "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
