blank_issues_enabled: true
contact_links:
  - name: 📚 Documentación
    url: https://github.com/MG-Octodemo/magero-store/blob/main/README.md
    about: Consulta la documentación del proyecto
  - name: 💬 Discusiones
    url: https://github.com/MG-Octodemo/magero-store/discussions
    about: Participa en discusiones con la comunidad
